# -*- coffee -*- -p
author: 'YC <yinso.chen@gmail.com>'
name: 'easydbi-pg'
description: 'easydbi binding for pg'
version: '0.1.1'
repository:
  type: 'git'
  url: 'git://github.com/yinso/easydbi-pg.git'
main: './lib/driver'
engines:
  node: '>= 0.8.4'
scripts:
  test: 'make test'
  prepublish: 'make'
dependencies:
  easydbi: '>=0.1.2'
  coffee-script: =1.8.0
  underscore: =1.7.0
  node-uuid: =1.4.1
  async: =0.9.0
  loglet: '>=0.1.1'
  pg: =4.1.0
devDependencies:
  testlet: '>= 0.2.0'
  'coffee-bean': '>=0.3.0'
  funclet: '>=0.1.0'
  
